### ISSUE TITLE
Update urls in password-generator.el header

### ISSUE THREAD

**Issue by duianto** [vandrlexay/emacs-password-genarator#4]
The urls in the `password-generator.el` header should probably be updated:
https://github.com/vandrlexay/emacs-password-genarator/blob/d754391d11d1d384833eb82fd34e02d2baec36cb/password-generator.el#L6

https://github.com/vandrlexay/emacs-password-genarator/blob/d754391d11d1d384833eb82fd34e02d2baec36cb/password-generator.el#L22

They do redirect to this repository.
But it would be better to point them to the current source.

**Comment by vandrlexay** [comment]
Fixed. Thank you.
